<a href="https://colab.research.google.com/github/hariseldon99/scientific-python-lectures/blob/master/Lecture-1-Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy -  multidimensional data arrays

## Introduction

The `numpy` package (module) is used in almost all numerical computation using Python. It is a package that provide high-performance vector, matrix and higher-dimensional data structures for Python. It is implemented in C and Fortran so when calculations are vectorized (formulated with vectors and matrices), performance is very good. 

To use `numpy` you need to import the module, using for example:

In [2]:
import numpy as np

Here, we have imported the numpy module into its own namespace in our programs. We have chosen to call this namespace `np`, which is the standard rule for using `numpy`, but any name will do, in principle.

In the `numpy` package the terminology used for vectors, matrices and higher-dimensional data sets is *array*. 



## Creating `numpy` arrays

There are a number of ways to initialize new numpy arrays, for example from

* a Python list or tuples
* using functions that are dedicated to generating numpy arrays, such as `arange`, `linspace`, etc.
* reading data from files

### From lists

For example, to create new vector and matrix arrays from Python lists we can use the `numpy.array` function.

In [3]:
# a vector: the argument to the array function is a Python list
v = np.array([1,2,3,4])

v

array([1, 2, 3, 4])

In [4]:
# a matrix: the argument to the array function is a nested Python list
M = np.array([[1, 2], [3, 4]])

M

array([[1, 2],
       [3, 4]])

The `v` and `M` objects are both of the type `ndarray` that the `numpy` module provides.

In [5]:
type(v), type(M)

(numpy.ndarray, numpy.ndarray)

The difference between the `v` and `M` arrays is only their shapes. We can get information about the shape of an array by using the `ndarray.shape` property.

In [6]:
v.shape

(4,)

In [7]:
M.shape

(2, 2)

The number of elements in the array is available through the `ndarray.size` property:

In [8]:
M.size

4

### Exercise 01:

Create a list of the numbers $1,2,3,4, \dots 1000$. Convert it to a numpy array and use array programming to multiply all the numbers by $2$. Use the code cell below. Note the presence of the '%%time' magic code in the beginning. This ensures that the code cell also yields the execution time in addition to the result.

In [ ]:
%%time # Type your code below this line


Now do the same thing to the original python list of numbers using a for-loop. Use the code cell below. 

In [14]:
%%time


5.42 µs ± 20.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


**Notabene**: These '%-magics' do not work in regular python, only with jupyter notebooks

If we want, we can explicitly define the type of the array data when we create it, using the `dtype` keyword argument: 

In [8]:
M = np.array([[1, 2], [3, 4]], dtype=complex)

M

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

Note that python uses 'j' to denote $\sqrt{-1}$ instead of the usual $i$. This is so that programmers can use the letter 'i' for other things. Complex numbers can be handled seamlessly in python.

### Exercise 02: 
Create a code cell below this cell and use numpy to build the three Pauli matrices. use the 'print()' function to show the output.

### Using array-generating functions

For larger arrays it is impractical to initialize the data manually, using explicit python lists. Instead we can use one of the many functions in `numpy` that generate arrays of different forms. Some of the more common are:

#### arange

In [ ]:
# create a range

x = np.arange(0, 24, 1) # arguments: start, stop, step
display(x)

y = np.arange(9)
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

### Exercise 03:

Using numpy, create a list of all even numbers from $1 - 100$. Also, create a list of all odd numbers in the same range, as well as a list of multiples of $4$.

The linspace() and logspace() functions create uniformly spaced list of numbers on a line. The first function does it on a linear scale, and the second function on a log-scale. 

In [13]:
# using linspace, both end points ARE included
np.linspace(0, 10, 25)

array([ 0.        ,  0.41666667,  0.83333333,  1.25      ,  1.66666667,
        2.08333333,  2.5       ,  2.91666667,  3.33333333,  3.75      ,
        4.16666667,  4.58333333,  5.        ,  5.41666667,  5.83333333,
        6.25      ,  6.66666667,  7.08333333,  7.5       ,  7.91666667,
        8.33333333,  8.75      ,  9.16666667,  9.58333333, 10.        ])

In [14]:
np.logspace(0, 10, 10, base=np.e)

array([1.00000000e+00, 3.03773178e+00, 9.22781435e+00, 2.80316249e+01,
       8.51525577e+01, 2.58670631e+02, 7.85771994e+02, 2.38696456e+03,
       7.25095809e+03, 2.20264658e+04])

### Exercise 04:

Create an array of $100$ uniformly spaced numbers from $-\pi - \pi$. Output the sine values of all these numbers. The value of $\pi$ can be gotten from `np.pi`, and the sine function from `np.sin()`

### Random data

In [15]:
from numpy import random

In [16]:
# uniform random numbers in [0,1]
random.rand(5,5)

array([[0.47788659, 0.41670169, 0.84203001, 0.70881597, 0.25652873],
       [0.97548813, 0.14794328, 0.50155178, 0.40717293, 0.04891298],
       [0.61969972, 0.02207024, 0.72019512, 0.82479015, 0.94119837],
       [0.78565818, 0.19102715, 0.73149646, 0.65548278, 0.78573564],
       [0.3098833 , 0.28110077, 0.22454148, 0.98272428, 0.54075712]])

In [17]:
# standard normal distributed random numbers
random.randn(5,5)

array([[-0.67607748,  2.33724368,  0.00675008, -3.24553573,  0.38879054],
       [-0.33798885, -1.68795526,  0.08100718, -1.18279995, -0.81466467],
       [ 0.29220914,  1.7218493 ,  0.11096174, -0.26061456,  1.37556784],
       [-1.13195232, -0.69071751,  0.04032949, -0.69025261, -0.96416825],
       [ 1.5412044 , -0.51828679,  1.37234766,  0.92356412, -1.71528985]])

### The diag function

In [18]:
# a diagonal matrix
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [19]:
# diagonal with offset from the main diagonal
np.diag([1,2,3], k=1) 

array([[0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0]])

### Arrays of zeros and ones

In [20]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [4]:
#Diagonal matrix with ones on the superdiagonal 
np.diag(np.ones(3), k=2) 

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [5]:
#Diagonal matrix with twos on the subdiagonal 
np.diag(2 * np.ones(3), k=-2)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [2., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 2., 0., 0.]])

### Exercise 05:

Prepare a $7 \times 7$ matrix with fixed numbers ($5$) on the $2^{nd}$ superdiagonal and subdiagonal.

## Manipulating arrays

### Indexing

We can index elements in an array using square brackets and indices:

In [47]:
# v is a vector, and has only one dimension, taking one index
v[0]

1

In [28]:
# M is a matrix, or a 2 dimensional array, taking two indices 
M[1,1]

0.8988330834933648

If we omit an index of a multidimensional array it returns the whole row (or, in general, a N-1 dimensional array) 

In [29]:
M

array([[0.15310045, 0.19570003, 0.00814879],
       [0.2112025 , 0.89883308, 0.42468023],
       [0.72065524, 0.89239399, 0.58122623]])

In [30]:
M[1]

array([0.2112025 , 0.89883308, 0.42468023])

The same thing can be achieved with using `:` instead of an index:

In [31]:
M[1,:] # row 1

array([0.2112025 , 0.89883308, 0.42468023])

In [32]:
M[:,1] # column 1

array([0.19570003, 0.89883308, 0.89239399])

We can assign new values to elements in an array using indexing:

In [33]:
M[0,0] = 1

In [34]:
M

array([[1.        , 0.19570003, 0.00814879],
       [0.2112025 , 0.89883308, 0.42468023],
       [0.72065524, 0.89239399, 0.58122623]])

In [35]:
# also works for rows and columns
M[1,:] = 0
M[:,2] = -1

In [36]:
M

array([[ 1.        ,  0.19570003, -1.        ],
       [ 0.        ,  0.        , -1.        ],
       [ 0.72065524,  0.89239399, -1.        ]])

### Index slicing

Index slicing is the technical name for the syntax `M[lower:upper:step]` to extract part of an array:

In [37]:
A = np.array([1,2,3,4,5])
A

array([1, 2, 3, 4, 5])

In [38]:
A[1:3]

array([2, 3])

Array slices are *mutable*: if they are assigned a new value the original array from which the slice was extracted is modified:

In [39]:
A[1:3] = [-2,-3]

A

array([ 1, -2, -3,  4,  5])

We can omit any of the three parameters in `M[lower:upper:step]`:

In [40]:
A[::] # lower, upper, step all take the default values

array([ 1, -2, -3,  4,  5])

In [41]:
A[::2] # step is 2, lower and upper defaults to the beginning and end of the array

array([ 1, -3,  5])

In [42]:
A[:3] # first three elements

array([ 1, -2, -3])

In [43]:
A[3:] # elements from index 3

array([4, 5])

Negative indices counts from the end of the array (positive index from the begining):

In [44]:
A = np.array([1,2,3,4,5])

In [45]:
A[-1] # the last element in the array

5

In [46]:
A[-3:] # the last three elements

array([3, 4, 5])

Index slicing works exactly the same way for multidimensional arrays:

In [47]:
A = np.array([[n+m*10 for n in range(5)] for m in range(5)])

A

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [48]:
# a block from the original array
A[1:4, 1:4]

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [49]:
# strides
A[::2, ::2]

array([[ 0,  2,  4],
       [20, 22, 24],
       [40, 42, 44]])

### Fancy indexing

Fancy indexing is the name for when an array or list is used in-place of an index: 

In [50]:
row_indices = [1, 2, 3]
A[row_indices]

array([[10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34]])

In [51]:
col_indices = [1, 2, -1] # remember, index -1 means the last element
A[row_indices, col_indices]

array([11, 22, 34])

We can also use index masks: If the index mask is an Numpy array of data type `bool`, then an element is selected (True) or not (False) depending on the value of the index mask at the position of each element: 

In [52]:
B = np.arange(5)
B

array([0, 1, 2, 3, 4])

In [53]:
row_mask = np.array([True, False, True, False, False])
B[row_mask]

array([0, 2])

In [54]:
# same thing
row_mask = np.array([1,0,1,0,0], dtype=bool)
B[row_mask]

array([0, 2])

This feature is very useful to conditionally select elements from an array, using for example comparison operators:

In [59]:
x = np.arange(0, 10, 0.5)
x

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [60]:
display(x > 5)

mask = (5 < x) * (x < 7.5)

display(mask)

array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True, False, False, False,
       False, False])

In [61]:
x[mask]

array([5.5, 6. , 6.5, 7. ])

In [62]:
# Masks can be literal also
display("Diplay occurrences of 4:", x[x==4])
display("Diplay occurrences of 4.x:", x[np.floor(x)==4])
display("Previous 2 cells in 1 line:", x[(5 < x) * (x < 7.5)])

'Diplay occurrences of 4:'

array([4.])

'Diplay occurrences of 4.x:'

array([4. , 4.5])

'Previous 2 cells in 1 line:'

array([5.5, 6. , 6.5, 7. ])

## Functions for extracting data from arrays and creating arrays

### where

The index mask can be converted to position index using the `where` function

In [63]:
indices = np.where(mask)

indices

(array([11, 12, 13, 14]),)

In [64]:
x[indices] # this indexing is equivalent to the fancy indexing x[mask]

array([5.5, 6. , 6.5, 7. ])

### diag

With the diag function we can also extract the diagonal and subdiagonals of an array:

In [65]:
print(A)
np.diag(A)

[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]
 [40 41 42 43 44]]


array([ 0, 11, 22, 33, 44])

In [66]:
np.diag(A, -1)

array([10, 21, 32, 43])

Part II
===========================
## Linear algebra

As we have seen above, **vectorizing code** is the key to writing efficient numerical calculation with Python/Numpy. That means that as much as possible of a program should be formulated in terms of matrix and vector operations, like matrix-matrix multiplication.

### Scalar-array operations

We can use the usual arithmetic operators to multiply, add, subtract, and divide arrays with scalar numbers.

In [67]:
v1 = np.arange(0, 5)
v1

array([0, 1, 2, 3, 4])

In [68]:
v1 * 2

array([0, 2, 4, 6, 8])

In [69]:
v1 + 2

array([2, 3, 4, 5, 6])

In [70]:
print(A)
A * 2, A + 2

[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]
 [40 41 42 43 44]]


(array([[ 0,  2,  4,  6,  8],
        [20, 22, 24, 26, 28],
        [40, 42, 44, 46, 48],
        [60, 62, 64, 66, 68],
        [80, 82, 84, 86, 88]]),
 array([[ 2,  3,  4,  5,  6],
        [12, 13, 14, 15, 16],
        [22, 23, 24, 25, 26],
        [32, 33, 34, 35, 36],
        [42, 43, 44, 45, 46]]))

### Matrix computations

In [92]:
#Get an identity matrix of any size
A = np.eye(9)
display(A)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [37]:
# reminder, the temperature dataset is stored in the data variable:
np.shape(data)

(77431, 7)

#### mean

In [38]:
data[:,3]

array([ -6.1, -15.4, -15. , ...,   4.9,   0.6,  -2.6])

In [39]:
# the temperature data is in column 3
np.mean(data[:,3])

6.197109684751585

The daily mean temperature in Stockholm over the last 200 years has been about 6.2 C.

#### standard deviations and variance

In [40]:
np.std(data[:,3]), np.var(data[:,3])

(8.282271621340573, 68.59602320966341)

print min and max

In [41]:
# lowest daily average temperature
data[:,3].min()

-25.8

In [42]:
# highest daily average temperature
data[:,3].max()

28.3

#### sum, prod, and trace

In [ ]:
d = np.arange(0, 10)
d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# sum up all elements
np.sum(d)

45

In [ ]:
# product of all elements
np.prod(d+1)

3628800

In [ ]:
# cummulative sum
np.cumsum(d)

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

In [ ]:
# cummulative product
np.cumprod(d+1)

array([      1,       2,       6,      24,     120,     720,    5040,
         40320,  362880, 3628800])

In [46]:
# same as: diag(A).sum()
display(M)
np.trace(M)

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

110

## Reshaping, resizing and stacking arrays

The shape of an Numpy array can be modified without copying the underlaying data, which makes it a fast operation even for large arrays.

In [130]:
M = np.array([[n+m*10 for n in range(5)] for m in range(5)])
M

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [131]:
n, m = M.shape

In [132]:
# Note that the new shape is passed as a tuple: '(a, n*m)' and not bare arguments: 'a, n+m'.
B = M.reshape((1,n*m))
B

array([[ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14, 20, 21, 22, 23, 24, 30,
        31, 32, 33, 34, 40, 41, 42, 43, 44]])

In [133]:
# Note the important difference in shape from the resultant array above
C = M.flatten()
print(C)

[ 0  1  2  3  4 10 11 12 13 14 20 21 22 23 24 30 31 32 33 34 40 41 42 43
 44]


In [134]:
B[0,0:5] = 5 # modify the array

B

array([[ 5,  5,  5,  5,  5, 10, 11, 12, 13, 14, 20, 21, 22, 23, 24, 30,
        31, 32, 33, 34, 40, 41, 42, 43, 44]])

In [135]:
M # and the original variable is also changed. B is only a different view of the same data

array([[ 5,  5,  5,  5,  5],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

We can also use the function `flatten` to make a higher-dimensional array into a vector. But this function creates a copy of the data.

In [136]:
B = M.flatten()

B

array([ 5,  5,  5,  5,  5, 10, 11, 12, 13, 14, 20, 21, 22, 23, 24, 30, 31,
       32, 33, 34, 40, 41, 42, 43, 44])

In [137]:
B[0:5] = 10

B

array([10, 10, 10, 10, 10, 10, 11, 12, 13, 14, 20, 21, 22, 23, 24, 30, 31,
       32, 33, 34, 40, 41, 42, 43, 44])

In [138]:
M # now M has not changed, because B's data is a copy of A's, not refering to the same data

array([[ 5,  5,  5,  5,  5],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

## Stacking and repeating arrays

Using function `np.repeat`, `np.tile`, `np.vstack`, `np.hstack`, and `np.concatenate` we can create larger vectors and matrices from smaller ones:

### tile and repeat

In [145]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [146]:
# repeat each element 3 times
np.repeat(a, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

In [147]:
# tile the matrix 3 times 
np.tile(a, 3)

array([[1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4]])

In [148]:
b = np.arange(10)
np.tile(b,2).reshape(2,10)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [149]:
# Can also be done with 'numpy.vstack()' function
np.vstack((b,b))

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

### concatenate

In [150]:
b = np.array([[5, 6]])
display(a,b)

array([[1, 2],
       [3, 4]])

array([[5, 6]])

In [151]:
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [152]:
np.concatenate((a, b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

### hstack and vstack

In [153]:
print(a)
print("\n")
print(b)

np.vstack((a,b))

[[1 2]
 [3 4]]


[[5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [154]:
np.hstack((a,b.T))

array([[1, 2, 5],
       [3, 4, 6]])