# Numpy -  multidimensional data arrays

## Introduction

The `numpy` package (module) is used in almost all numerical computation using Python. It is a package that provide high-performance vector, matrix and higher-dimensional data structures for Python. 

To use `numpy` you need to import the module, using for example:

In [1]:
import numpy as np

Here, we have imported the numpy module into its own namespace in our programs. We have chosen to call this namespace `np`, which is the standard rule for using `numpy`, but any name will do, in principle.

In the `numpy` package the terminology used for vectors, matrices and higher-dimensional data sets is *array*. 



## Creating `numpy` arrays

There are a number of ways to initialize new numpy arrays, for example from

* a Python list or tuples
* using functions that are dedicated to generating numpy arrays, such as `arange`, `linspace`, etc.
* reading data from files

### From lists

For example, to create new vector and matrix arrays from Python lists we can use the `numpy.array` function.

In [3]:
# a vector: the argument to the array function is a Python list
v = np.array([1,2,3,4])

v

array([1, 2, 3, 4])

In [4]:
# a matrix: the argument to the array function is a nested Python list
M = np.array([[1, 2], [3, 4]])

M

array([[1, 2],
       [3, 4]])

The `v` and `M` objects are both of the type `ndarray` that the `numpy` module provides.

In [5]:
type(v), type(M)

(numpy.ndarray, numpy.ndarray)

The difference between the `v` and `M` arrays is only their shapes. We can get information about the shape of an array by using the `ndarray.shape` property.

In [6]:
v.shape

(4,)

In [7]:
M.shape

(2, 2)

The number of elements in the array is available through the `ndarray.size` property:

In [8]:
M.size

4

If we want, we can explicitly define the type of the array data when we create it, using the `dtype` keyword argument: 

In [8]:
M = np.array([[1, 2], [3, 4]], dtype=complex)

M

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

Note that python uses 'j' to denote $\sqrt{-1}$ instead of the usual $i$. This is so that programmers can use the letter 'i' for other things. Complex numbers can be handled seamlessly in python.

### Exercise 01:

   1. In the code cell below, create a list of the numbers $1,2,3,4, \dots 10,000$ and call it 'a'. Then, Convert it to a numpy array and use array programming to multiply all the numbers by $2$ and output the result. 
   2. Use the code cell below and use numpy to build the three Pauli matrices. use the 'print()' function to show the output.

### Using array-generating functions

For larger arrays it is impractical to initialize the data manually, using explicit python lists. Instead we can use one of the many functions in `numpy` that generate arrays of different forms. Some of the more common are:

#### arange

In [3]:
# create a range
x = np.arange(0, 24, 1) # arguments: start, stop, step
display(x)

y = np.arange(9)
display(y)

z = np.arange(0, 20, 2)
display(z)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

The linspace() and logspace() functions create uniformly spaced list of numbers on a line. The first function does it on a linear scale, and the second function on a log-scale. 

In [13]:
# using linspace, both end points ARE included
np.linspace(0, 10, 25)

array([ 0.        ,  0.41666667,  0.83333333,  1.25      ,  1.66666667,
        2.08333333,  2.5       ,  2.91666667,  3.33333333,  3.75      ,
        4.16666667,  4.58333333,  5.        ,  5.41666667,  5.83333333,
        6.25      ,  6.66666667,  7.08333333,  7.5       ,  7.91666667,
        8.33333333,  8.75      ,  9.16666667,  9.58333333, 10.        ])

In [14]:
np.logspace(0, 10, 10, base=np.e)

array([1.00000000e+00, 3.03773178e+00, 9.22781435e+00, 2.80316249e+01,
       8.51525577e+01, 2.58670631e+02, 7.85771994e+02, 2.38696456e+03,
       7.25095809e+03, 2.20264658e+04])

### Exercise 02:

1. Using numpy, create a list of all even numbers from $1 - 100$. Also, create a list of all odd numbers in the same range, as well as a list of multiples of $4$.
2. Create an array of $100$ uniformly spaced numbers in the interval $\left[-\pi , \pi\right]$.  The value of $\pi$ can be gotten from `np.pi`.

### The diag function:

The `np.diag()` function can be used to create a matrix and populate it with a given vector along a desired diagonal.

In [18]:
# a diagonal matrix
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [19]:
# diagonal with offset from the main diagonal
np.diag([1,2,3], k=1) 

array([[0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0]])

With the diag function we can also extract the diagonal and subdiagonals of an array:

In [108]:
A = np.random.rand(3,3)
A

array([[0.1097733 , 0.47724435, 0.46572997],
       [0.18731052, 0.68840323, 0.05433925],
       [0.08983981, 0.08060106, 0.70280683]])

In [109]:
np.diag(A)

array([0.1097733 , 0.68840323, 0.70280683])

In [110]:
np.diag(A, k=-1)

array([0.18731052, 0.08060106])

### Arrays of zeros and ones

Homogeneous arrays (where all the values are the same) of any size and shape can be easily created.

In [40]:
np.zeros(4)

array([0., 0., 0., 0.])

In [20]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [41]:
np.ones(4)

array([1., 1., 1., 1.])

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

We can combine multiple functions to create more complex arrays.

In [4]:
#Diagonal matrix with ones on the superdiagonal 
np.diag(np.ones(3), k=2) 

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [5]:
#Diagonal matrix with twos on the subdiagonal 
np.diag(2 * np.ones(3), k=-2)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [2., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 2., 0., 0.]])

### Exercise 03:

Prepare a $7 \times 7$ matrix with fixed numbers ($5$) on the $2^{nd}$ superdiagonal and subdiagonal.

## Manipulating arrays

### Indexing

We can index elements in an array using square brackets and indices:

In [42]:
v = np.random.random(10) # 10 random numbers from a uniform distribution in [0,1]
print(v)
# v is a vector, and has only one dimension, taking one index
v[0]

[0.39796982 0.97571643 0.14047112 0.36550337 0.19483888 0.68575146
 0.57990971 0.85476018 0.01678117 0.39794892]


0.3979698156787721

In [44]:
M = np.random.random((4,4))  # M is a 4 X 4 matrix, or a 2 dimensional array, taking two indices 
print(M)

M[1,1]

[[0.8187199  0.65338288 0.33229777 0.81532183]
 [0.555501   0.16744827 0.43188729 0.70565032]
 [0.28648923 0.4375707  0.16593807 0.55852771]
 [0.17304955 0.66272481 0.30567052 0.94329551]]


0.16744826663043788

If we omit an index of a multidimensional array it returns the whole row (or, in general, a N-1 dimensional array) 

In [45]:
M

array([[0.8187199 , 0.65338288, 0.33229777, 0.81532183],
       [0.555501  , 0.16744827, 0.43188729, 0.70565032],
       [0.28648923, 0.4375707 , 0.16593807, 0.55852771],
       [0.17304955, 0.66272481, 0.30567052, 0.94329551]])

In [46]:
M[1]

array([0.555501  , 0.16744827, 0.43188729, 0.70565032])

The same thing can be achieved with using `:` instead of an index:

In [47]:
M[1,:] # row 1

array([0.555501  , 0.16744827, 0.43188729, 0.70565032])

In [48]:
M[:,1] # column 1

array([0.65338288, 0.16744827, 0.4375707 , 0.66272481])

We can assign new values to elements in an array using indexing:

In [49]:
M[0,0] = 1

In [50]:
M

array([[1.        , 0.65338288, 0.33229777, 0.81532183],
       [0.555501  , 0.16744827, 0.43188729, 0.70565032],
       [0.28648923, 0.4375707 , 0.16593807, 0.55852771],
       [0.17304955, 0.66272481, 0.30567052, 0.94329551]])

In [51]:
# also works for rows and columns
M[1,:] = 0
M[:,2] = -1

In [52]:
M

array([[ 1.        ,  0.65338288, -1.        ,  0.81532183],
       [ 0.        ,  0.        , -1.        ,  0.        ],
       [ 0.28648923,  0.4375707 , -1.        ,  0.55852771],
       [ 0.17304955,  0.66272481, -1.        ,  0.94329551]])

### Index slicing

Index slicing is the technical name for the syntax `M[lower:upper:step]` to extract part of an array:

In [37]:
A = np.array([1,2,3,4,5])
A

array([1, 2, 3, 4, 5])

In [38]:
A[1:3]

array([2, 3])

Array slices are *mutable*: if they are assigned a new value the original array from which the slice was extracted is modified:

In [39]:
A[1:3] = [-2,-3]

A

array([ 1, -2, -3,  4,  5])

We can omit any of the three parameters in `M[lower:upper:step]`:

In [40]:
A[::] # lower, upper, step all take the default values

array([ 1, -2, -3,  4,  5])

In [41]:
A[::2] # step is 2, lower and upper defaults to the beginning and end of the array

array([ 1, -3,  5])

In [42]:
A[:3] # first three elements

array([ 1, -2, -3])

In [43]:
A[3:] # elements from index 3

array([4, 5])

Negative indices counts from the end of the array (positive index from the begining):

In [44]:
A = np.array([1,2,3,4,5])

In [45]:
A[-1] # the last element in the array

5

In [46]:
A[-3:] # the last three elements

array([3, 4, 5])

Index slicing works exactly the same way for multidimensional arrays:

In [47]:
A = np.array([[n+m*10 for n in range(5)] for m in range(5)])

A

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [48]:
# a block from the original array
A[1:4, 1:4]

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [49]:
# strides
A[::2, ::2]

array([[ 0,  2,  4],
       [20, 22, 24],
       [40, 42, 44]])

Here's something interesting. We can use index slicing to extract diagonals and anti-diagonals of a matrix.

In [112]:
A = np.random.rand(5,5)
A

array([[0.23739847, 0.73347351, 0.12733749, 0.33997725, 0.77604993],
       [0.88018944, 0.5973701 , 0.20135709, 0.42591759, 0.22129381],
       [0.40073728, 0.75331752, 0.77766081, 0.98397582, 0.72918257],
       [0.90166093, 0.46368833, 0.95693924, 0.16777689, 0.23720114],
       [0.47464523, 0.08948455, 0.35870972, 0.84836818, 0.31748749]])

In [116]:
#Extract diagonal
A[::-1,::-1]

array([[0.31748749, 0.84836818, 0.35870972, 0.08948455, 0.47464523],
       [0.23720114, 0.16777689, 0.95693924, 0.46368833, 0.90166093],
       [0.72918257, 0.98397582, 0.77766081, 0.75331752, 0.40073728],
       [0.22129381, 0.42591759, 0.20135709, 0.5973701 , 0.88018944],
       [0.77604993, 0.33997725, 0.12733749, 0.73347351, 0.23739847]])

**Fancy indexing** is the name for when an array or list is used in-place of an index: 

In [50]:
row_indices = [1, 2, 3]
A[row_indices]

array([[10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34]])

In [51]:
col_indices = [1, 2, -1] # remember, index -1 means the last element
A[row_indices, col_indices]

array([11, 22, 34])

### Exercise 04:

Execute the cell below to create the $3 \times 4 \times 4$ array named 'data', which is an array of three $4\times 4$ matrices.

In [152]:
data = np.array([[[ 1.,  2.,  3.,  4.],
                [ 5.,  6.,  7.,  8.],
                [ 9., 10., 11., 12.],
                [13., 14., 15., 16.]],
        
                [[17., 18., 19., 20.],
                [21., 22., 23., 24.],
                [25., 26., 27., 28.],
                [29., 30., 31., 32.]],

                [[33., 34., 35., 36.],
                [37., 38., 39., 40.],
                [41., 42., 43., 44.],
                [45., 46., 47., 48.]]])

Now, index or slice this array to obtain the following:

1. $20.0$
2. The array $\left[9.10,11,12\right]$
3. The following square matrix
   \begin{pmatrix}
   33 & 34 & 35 & 36\\
   37 & 38 & 39 & 40\\
   41 & 42 & 43 & 44\\
   45 & 46 & 47 & 48
   \end{pmatrix}
4. The following sub-matrix
   \begin{pmatrix}
   18 & 19 \\
   22 & 23
   \end{pmatrix}

## Linear Algebra with arrays
As we have seen above, **vectorizing code** is the key to writing efficient numerical calculation with Python/Numpy. That means that as much as possible of a program should be formulated in terms of matrix and vector operations, like matrix-matrix multiplication.

### Scalar-array operations

We can use the usual arithmetic operators to multiply, add, subtract, and divide arrays with scalar numbers.

In [ ]:
v1 = np.arange(0, 5)
v1

array([0, 1, 2, 3, 4])

In [ ]:
v1 * 2

array([0, 2, 4, 6, 8])

In [ ]:
v1 + 2

array([2, 3, 4, 5, 6])

In [ ]:
print(A)
A * 2, A + 2

[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]
 [40 41 42 43 44]]


(array([[ 0,  2,  4,  6,  8],
        [20, 22, 24, 26, 28],
        [40, 42, 44, 46, 48],
        [60, 62, 64, 66, 68],
        [80, 82, 84, 86, 88]]),
 array([[ 2,  3,  4,  5,  6],
        [12, 13, 14, 15, 16],
        [22, 23, 24, 25, 26],
        [32, 33, 34, 35, 36],
        [42, 43, 44, 45, 46]]))

### Element-wise array-array operations

When we add, subtract, multiply and divide arrays with each other, the default behaviour is **element-wise** operations:

In [ ]:
print(A)
A * A # element-wise multiplication

[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]
 [40 41 42 43 44]]


array([[   0,    1,    4,    9,   16],
       [ 100,  121,  144,  169,  196],
       [ 400,  441,  484,  529,  576],
       [ 900,  961, 1024, 1089, 1156],
       [1600, 1681, 1764, 1849, 1936]])

In [ ]:
print(v1)
v1 * v1

[0 1 2 3 4]


array([ 0,  1,  4,  9, 16])

If we multiply arrays with compatible shapes, we get an element-wise multiplication of each row:

In [ ]:
A.shape, v1.shape

((5, 5), (5,))

In [ ]:
A * v1

array([[  0,   1,   4,   9,  16],
       [  0,  11,  24,  39,  56],
       [  0,  21,  44,  69,  96],
       [  0,  31,  64,  99, 136],
       [  0,  41,  84, 129, 176]])

### Matrix algebra

What about matrix mutiplication? There are many ways. The simplest way is to use the `@` idiom, which applies a matrix-matrix, matrix-vector, or inner vector multiplication to its two arguments: 

In [ ]:
A @ A # Matrix-Matrix product

array([[ 300,  310,  320,  330,  340],
       [1300, 1360, 1420, 1480, 1540],
       [2300, 2410, 2520, 2630, 2740],
       [3300, 3460, 3620, 3780, 3940],
       [4300, 4510, 4720, 4930, 5140]])

In [ ]:
A @ v1 # Matrix-Vector product

array([ 30, 130, 230, 330, 430])

In [ ]:
v1 @ v1 # Inner Product (Real vectors)

30

In [ ]:
vc = np.array([0 + 1.j, 1 + 2.j, 4 + 3.j, 1 + 5.j, 0])
vc.conjugate() @ vc

(57+0j)

In [ ]:
vc + A @ v1

array([ 30.+1.j, 131.+2.j, 234.+3.j, 331.+5.j, 430.+0.j])

The transpose of an array can be obtained with the `.T` method.

In [58]:
A= np.arange(25).reshape(5,5) + (1j) * np.arange(25, 50).reshape(5,5)
print(A)

[[ 0.+25.j  1.+26.j  2.+27.j  3.+28.j  4.+29.j]
 [ 5.+30.j  6.+31.j  7.+32.j  8.+33.j  9.+34.j]
 [10.+35.j 11.+36.j 12.+37.j 13.+38.j 14.+39.j]
 [15.+40.j 16.+41.j 17.+42.j 18.+43.j 19.+44.j]
 [20.+45.j 21.+46.j 22.+47.j 23.+48.j 24.+49.j]]


In [59]:
B = A.T
print(B)

[[ 0.+25.j  5.+30.j 10.+35.j 15.+40.j 20.+45.j]
 [ 1.+26.j  6.+31.j 11.+36.j 16.+41.j 21.+46.j]
 [ 2.+27.j  7.+32.j 12.+37.j 17.+42.j 22.+47.j]
 [ 3.+28.j  8.+33.j 13.+38.j 18.+43.j 23.+48.j]
 [ 4.+29.j  9.+34.j 14.+39.j 19.+44.j 24.+49.j]]


To obtain the Hermitian conjugate of an array, simply transpose it and obtain the complex conjugate

In [60]:
A_dagger = A.T.conj()
print(A_dagger)

[[ 0.-25.j  5.-30.j 10.-35.j 15.-40.j 20.-45.j]
 [ 1.-26.j  6.-31.j 11.-36.j 16.-41.j 21.-46.j]
 [ 2.-27.j  7.-32.j 12.-37.j 17.-42.j 22.-47.j]
 [ 3.-28.j  8.-33.j 13.-38.j 18.-43.j 23.-48.j]
 [ 4.-29.j  9.-34.j 14.-39.j 19.-44.j 24.-49.j]]


### Exercise 05:
1. Use NumPy to create the three Pauli matrices $\sigma_x, \sigma_y, \sigma_z$ and show that the commutation relations $\left[\sigma_x, \sigma_y\right] = i \sigma_z$ and $\left[\sigma_z, \sigma_y\right] = -i \sigma_x$, hold true.
2. Create the following matrix and vector and multiply them in the usual matrix-vector way.
\begin{align*}
A & = \begin{pmatrix}
0 & 1 & 0 & 0\\
1 & 0 & 0 & 0\\
0 & 0 & 0 & 1\\
0 & 0 & 1 & 0
\end{pmatrix}\\
\vert{v}\rangle &= \begin{pmatrix}
1\\
-1\\
1\\
-1
\end{pmatrix}
\end{align*}
3. If a unitary transformation $U$ is given by 
\begin{pmatrix}
0 & 0 & 0 & 1\\
0 & 0 & -1 & 0\\
0 & -1 & 0 & 0\\
1 & 0 & 0 & 0
\end{pmatrix},
then, compute the transformed matrix $A^\prime = UAU^T$ and vector $\vert{v^\prime}\rangle = U \vert{v}\rangle$. Show that $A^\prime\vert{v^\prime}\rangle = U\left(A\vert{v}\rangle\right)$.

### Reshaping arrays
Arrays can be reshaped with the new shape supplied as a tuple to the `.reshape` method. For instance, a $4 \times 4$ array can be reshaped into a $8 \times 2$ array as follows

In [62]:
A = np.random.random((4,4))
A

array([[0.66190534, 0.91136482, 0.20079742, 0.36789149],
       [0.0690701 , 0.04662735, 0.81528806, 0.1804445 ],
       [0.58777082, 0.39515522, 0.17799737, 0.78331803],
       [0.40864391, 0.79105166, 0.63214028, 0.69704231]])

In [66]:
B = A.reshape(8,2)
B

array([[0.66190534, 0.91136482],
       [0.20079742, 0.36789149],
       [0.0690701 , 0.04662735],
       [0.81528806, 0.1804445 ],
       [0.58777082, 0.39515522],
       [0.17799737, 0.78331803],
       [0.40864391, 0.79105166],
       [0.63214028, 0.69704231]])

In [67]:
C = A.reshape(2,8)
C

array([[0.66190534, 0.91136482, 0.20079742, 0.36789149, 0.0690701 ,
        0.04662735, 0.81528806, 0.1804445 ],
       [0.58777082, 0.39515522, 0.17799737, 0.78331803, 0.40864391,
        0.79105166, 0.63214028, 0.69704231]])

Arrays of any shape can be flattened to vectors in row-major order.

In [68]:
V = A.flatten()
V

array([0.66190534, 0.91136482, 0.20079742, 0.36789149, 0.0690701 ,
       0.04662735, 0.81528806, 0.1804445 , 0.58777082, 0.39515522,
       0.17799737, 0.78331803, 0.40864391, 0.79105166, 0.63214028,
       0.69704231])

### Computations on arrays

NumPy has special functions that can perform computations on arrays to yield numbers.

In [122]:
a = np.arange(1, 6)
a

array([1, 2, 3, 4, 5])

In [123]:
# Sums over all elements
np.sum(a)

15

In [124]:
# Multiplies all elements
np.prod(a)

120

These can be combined on the fly with scalar and array operations

In [126]:
print(a+1)
np.sum(a+1)

[2 3 4 5 6]


20

In [128]:
a = np.array([1,2,3,2,1])
b = np.array([2,3,4,5,4])

print(a @ b)
np.sum(a * b)

34


34

You can also perform operations on array slices. For instance:

In [10]:
M = np.arange(1, 10).reshape(3,3)
display(M)

display(M[1:3, 1:3])
s1 = np.sum(M[1:3, 1:3])
display(s1)

display(np.diag(M))
s2 = np.sum(np.diag(M))
display(s2)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

array([[5, 6],
       [8, 9]])

28

array([1, 5, 9])

15

In [14]:
# Averages (mean) and standard deviations (std) can also me computed
a = np.random.rand(4)
display(a)
display(np.mean(a))
display(np.std(a))

array([0.16354624, 0.5589451 , 0.74464038, 0.03487922])

0.375502734852901

0.28760373511116877

In [16]:
# Note that random matrices of any shape can be created

a = np.random.rand(3,3)
display(a)

array([[0.9634749 , 0.71714948, 0.5249472 ],
       [0.40292622, 0.39014927, 0.15456273],
       [0.39922343, 0.5076424 , 0.57344493]])

In [148]:
# A random array with samples chosen from a Gaussian (Normal) distribution should yield close to zero mean and unit standard deviation
a = np.random.normal(size=10000)
a

array([ 0.99856939, -0.27526011, -1.05217683, ..., -0.40203312,
        0.63862949, -0.4877782 ])

In [149]:
np.mean(a), np.std(a)

(0.0036212158919876132, 0.9945376451413487)

Finally, there are NumPy functions for computing determinants and traces of matrices. The determinant function is in the `np.linalg` submodule.

In [12]:
A = np.array([[1,2], 
              [3,4]])

np.linalg.det(A)

-2.0000000000000004

In [13]:
np.trace(A)

5

### Exercise 06:

1. Use the `np.sum()` function to demonstrate the following relation for $N=5, 10, 20$
   \begin{equation*}
   \sum^N_{n=1} n^2 = \frac{1}{6}\;N\left(N+1\right)\left(2N+1\right)
   \end{equation*}
2. Create two random $5\times 5$ matrices $A,B$ and show that $\rm{Tr}\left[AB\right] = \rm{Tr}\left[BA\right]$.