Introduction
==========
The basics of Python are fairly simple to learn, if you already know how another structured language (like C) works. So we will walk through these basics here. This is only intended to be a quick overview, not a deep dive into how Python works.

One big difference between C and Python is that C is _compiled_ while Python is _interpreted_. This means that to run a C program, you first have to compile it (e.g., with `gcc`) and _then_ run it; but once you compile the program, you have a standalone executable (e.g., `a.out`). With a Python program, you do not have to compile the program but to _run_ the program you need to run it in the Python interpreter (e.g., `> python hw0.py`)

In practice, at least for this class, this distinction will not really matter (it can matter more once you get to long-running programs that operate over large amounts of data).

This material is available online at [https://bit.ly/python4c](https://bit.ly/python4c).


Variables and Types
==============

Perhaps the biggest difference between C and Python is that C variables are _statically typed_ -- you need to say whether a variable `x` is an `int` or a `float` right up front. In Python, you don't:

In [ ]:
x = 1
type(x)

int

Note that this means that we don't need to "declare" variables -- we can just use them whenever we need to.

What's interesting about Python, though, is that while we say the type of `x` is an `int`, what's really happening is that `x` is a reference to an _integer object_, which happes to have the value 1. `x` itself doesn't have a fixed type. We can re-assign it:

In [ ]:
x = 1.2
type(x)

float

You can even make `x` a string:

In [ ]:
x = "hello"
type(x)

str

Python does its type checking _dynamically_. It will not tell you until you try to do something with a variable whether the operation is legal or not:

In [ ]:
len(x) #this will work because x is a string

5

In [ ]:
x = 1.2
len(x) #what will happen here?

TypeError: object of type 'float' has no len()

Python will also perform _type coercion_: when it makes sense, it will convert an object from one type to another to let an operation work:

In [ ]:
p = 1
print(type(p)) #the parentheses around the argument to print are optional

q = .2
print (type(q))

r = p + q
print (type(r))
print ("value of r: {}".format(r)) #compare this to printf!

<class 'int'>
<class 'float'>
<class 'float'>
value of r: 1.2


Idiomatic Python
===========

Another powerful feature of python is its *idiomatic* nature. That is to say, there are many simple built-in instructions for complex tasks. For instance, suppose we set variables a=2 and b=3, and seek to interchange them to a=3, b=2. Then, in C, we'd have to do something like this:


In [ ]:
a = 2
b = 3
print(a,b)
scratch = 0 # temporary scratch space
scratch = a
a = b
b = scratch
print(a,b)
del(scratch) # delete scratch from memory

2 3
3 2


However, python offers a simple idiom for this using *tuples* as follows

In [ ]:
a = 2
b = 3
print(a,b)
a,b = b,a
print(a,b)

2 3
3 2


No need to explicitly create scratch storage, python does these things automatically.

Other idiomatic tools, like array programming, scientific computing, graph plotting etc. can be done in python using external tools like `numpy` (Numerical Python), `scipy` (Scientific Python) and `matplotlib` (MATLAB-like plotting library). We'll discuss these later.

Arithmetic
=======
Arithmetic in python is more or less the same as C, with the same precedence of operators.

In [ ]:
print( 2+3/4 )
print( (2+3)/4 )

a = 5
b = 3.5
c = 1.25

d = a * b + c
g = a * (b+c)
print(d,g)

print(2*d, d**2, a % 2)

2.75
1.25
18.75 23.75
37.5 351.5625 1


Advanced functions can be imported from the `math` module in python, or from `numpy` (Numerical Python module).

In [ ]:
import math as m

theta = m.pi/2
print(m.sin(theta))

theta = m.pi/4
print(m.cos(theta))

1.0
0.7071067811865476


In [ ]:
import numpy as np

theta = np.pi/4
print(np.cos(theta))
print(np.cosh(theta))

x = 10
print(np.log(x)) #This is to the base 'e'

0.7071067811865477
1.324609089252006
2.3025850929940455


Control statements
=======

Control statements in Python look a lot like their counterparts in C: `if` statements, `while` loops, `for` loops. The _biggest_ difference is that in Python _whitespace matters_. We do not use `{` and `}` to separate blocks. Instead, we use colons (`:`) to mark the beginning of a block and indentation to mark what is in the block.

**If Statements**

Here is the equivalent of the C statement:

`if (r < 3)
    printf("x\n");
else printf("y\n");`

In [ ]:
if r < 3:
    print("x")
else:
    print("y")

y


And an example of multiline blocks:

In [ ]:
if r < 1:
    print("x")
    print("less than 1")
elif r < 2:
    print("y")
    print ("less than 2")
elif r < 3:
    print ("z")
    print ("less than 3")
else:
    print("w")
    print("otherwise!")

w
otherwise!


**While Loops**

`while` loops are similar:

In [ ]:
x = 1
y = 1
while (x <= 10) :
    y *= x
    x += 1

print(y)

3628800


In [ ]:
x = 1
total = 0
while (x <= 10):
    total += x
    x +=1

print(total)

55


**For Loops**

`for` loops are a little trickier. They do _not_ take the same form as C for loops. Instead, for loops iterate over collections in Python (e.g., lists). These are more like `foreach` loops that you might see in other languages (or the `for (x : list)` construct you see in Java). So let's start by talking about lists:

In [ ]:
data = [1, 4, 9, 0, 4, 2, 6, 1, 2, 8, 4, 5, 0, 7]
#This is a python 'list'. It is similar to a C array, except it can contain anything.

print(data)

[1, 4, 9, 0, 4, 2, 6, 1, 2, 8, 4, 5, 0, 7]


In [ ]:
hist = 3 * [2,3,4]
print(hist)

[2, 3, 4, 2, 3, 4, 2, 3, 4]


Lists work like a combination of arrays in C (you can access them using `[]`) and lists (you can append elements, remove elements, etc.)

In [ ]:
length = len(data)
print(f"data length: {length} data[{length-1}] = {data[length-1]}")
#Note that this is a format string. The f"..." is the standard syntax for the format strings.
#These can contain python variables, enclosed with curly brackets. Output will be the corresponding values.

data length: 14 data[13] = 7


In [ ]:
data.append(8)
length = len(data)
print(f"data length: {length} data[{length-1}] = {data[length-1]}")

data length: 15 data[14] = 8


You can then _iterate_ over the elements of the list:

In [ ]:
for d in data :
    print(d)

1
4
9
0
4
2
6
1
2
8
4
5
0
7
8


In [ ]:
for d in data :
    hist[int(d/2)] += 1
print(hist)

[6, 5, 8, 4, 6, 4, 2, 3, 4]


How do you write a `for` loop with an index variable that counts from 0 to 4, like you might in C?
`for (int i = 0; i < 5; i++)`

Use the standard function `range`, which generates a list with values that count from a lower bound to an upper bound:

In [ ]:
r = range(0,5)
print(r)

range(0, 5)


In [ ]:
d = []
for i in r:
    d.append(2*i)
print(d)

[0, 2, 4, 6, 8]


In [ ]:
import numpy as np

a = np.arange(0,5)

print(2*a)

[0 2 4 6 8]


You can use the 'array' data type from `numpy` to perform vector matrix operations without needing explicit loops.

In [ ]:
# Multiply all elements of an array by 3

a = np.array([5,2,3,1])
print(3*a)

[15  6  9  3]


In [ ]:
# Multiply all elements of a vector by 3 like you would do in C

a = np.array([5,2,3,1])

b = np.zeros_like(a)
for i in range(4):
    b[i] = 3 * a[i]

print(b)

[15  6  9  3]


In [ ]:
#Find the inner product between two vectors

a = np.array([5,2,3,1])
b = np.array([2,3,5,1])
print(a @ b)

32


In [ ]:
#Find the inner product between two vectors using a loop like you would do in C

a = np.array([5,2,3,1])
b = np.array([2,3,5,1])

prod = 0

for i in range(4):
    prod += a[i] * b[i]

print(prod)

32


Functions
=======

Basic functions in Python work a lot like functions in C. The key differences are:
1. You don't have to specify a return type. In fact, you can return more than one thing!
2. You don't have to specify the types of the arguments
3. When calling functions, you can name the arguments (and thus change the order of the call)

In [ ]:
def foo(x) :
    return x * 2

print(foo(10))

20


In [ ]:
def foo2(x) :
    return x * 2, x * 4

(a, b) = foo2(10)
print(a, b)

20 40


In [ ]:
def foo3(x, y) :
    return 2 * x + y

print(foo3(7, 10))
print(foo3(y = 10, x = 7))

24
24
